server:
  port: ${SERVER_PORT:7092}
  static: ./static
service:
  name: ${SERVICE_NAME:ring}
  prod: ${PROD:false}
database:
  dsn: ${DATABASE_DSN:postgres://postgres:p0proxima@postgres:5432/ring?sslmode=disable&application_name=ring}